name: Build iOS App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build .app and .ipa
        run: |
          cd 3105-main
          xcodebuild build \
            -project ThreeOneOSFive.xcodeproj \
            -scheme ThreeOneOSFive \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath ./build_output \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          # Đóng gói luôn thành file .ipa
          mkdir -p Payload
          cp -r ./build_output/Build/Products/Release-iphoneos/*.app Payload/
          zip -r Delta_3105.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Delta_3105_IPA
          path: 3105-main/Delta_3105.ipa
